# Generated by Django 3.2.6 on 2022-05-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='', max_length=225)),
                ('city', models.CharField(default='', max_length=225)),
                ('state', models.CharField(default='', max_length=225)),
                ('postal_code', models.CharField(default='', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acct_num', models.CharField(default='', max_length=225)),
                ('Bank_name', models.CharField(default='', max_length=225)),
                ('IFSC_code', models.CharField(default='', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='PastJobExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(default='', max_length=225)),
                ('job_role', models.CharField(default='', max_length=225)),
                ('experience', models.CharField(default='', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=225)),
                ('dob', models.DateField()),
                ('blood_grp', models.CharField(default='', max_length=5)),
                ('contact_num', models.CharField(default='', max_length=225)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_name', models.CharField(default='', max_length=225)),
                ('passing_yr', models.CharField(default='', max_length=225)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('aadhar_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Is_active', models.BooleanField(default=True)),
                ('address', models.ManyToManyField(to='accounts.Address')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bank')),
                ('past_job_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pastjobexp')),
                ('prsnl_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.personaldetails')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.qualification')),
            ],
        ),
    ]
