# Generated by Django 3.2.6 on 2022-05-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_aadhar_address_bank_pastjobexp_personaldetails_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='percentage',
            field=models.IntegerField(max_length=3),
        ),
    ]
